In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from sklearn.linear_model import LinearRegression


In [2]:
# Load the data and store it in dataframe df:
file_path = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/automobileEDA.csv"
df = pd.read_csv(file_path)
df.head()

symboling  normalized-losses         make aspiration num-of-doors  \
0          3                122  alfa-romero        std          two   
1          3                122  alfa-romero        std          two   
2          1                122  alfa-romero        std          two   
3          2                164         audi        std         four   
4          2                164         audi        std         four   

    body-style drive-wheels engine-location  wheel-base    length  ...  \
0  convertible          rwd           front        88.6  0.811148  ...   
1  convertible          rwd           front        88.6  0.811148  ...   
2    hatchback          rwd           front        94.5  0.822681  ...   
3        sedan          fwd           front        99.8  0.848630  ...   
4        sedan          4wd           front        99.4  0.848630  ...   

   compression-ratio  horsepower  peak-rpm city-mpg highway-mpg    price  \
0                9.0       111.0    5000.0       21          27  13495.0   
1                9.0       111.0    5000.0       21          27  16500.0   
2                9.0       154.0    5000.0       19          26  16500.0   
3               10.0       102.0    5500.0       24          30  13950.0   
4                8.0       115.0    5500.0       18          22  17450.0   

  city-L/100km  horsepower-binned  diesel  gas  
0    11.190476             Medium       0    1  
1    11.190476             Medium       0    1  
2    12.368421             Medium       0    1  
3     9.791667             Medium       0    1  
4    13.055556             Medium       0    1  

[5 rows x 29 columns]

Create the linear regression object:

In [3]:
lm = LinearRegression()
lm

LinearRegression()

In [4]:
X = df[['highway-mpg' ]] # predictor
y = df['price'] # target

#Fit the linear model using highway-mpg:

lm.fit(X,y)

LinearRegression()

In [5]:
# We can output a prediction:
y_hat = lm.predict(X)
y_hat[0:5]

array([16236.50464347, 16236.50464347, 17058.23802179, 13771.3045085 ,
       20345.17153508])

In [6]:
# What is the value of the intercept (a)?

#lm.intercept_


round((lm.intercept_), 2)

38423.31

In [7]:
# What is the value of the slope (b)?
lm.coef_

array([-821.73337832])

#### Question #1 a): 
Create a linear regression object called "lm1".



In [8]:
lm1 = LinearRegression()
lm1

LinearRegression()

#### Question #1 b): 
Train the model using "engine-size" as the independent variable and "price" as the dependent variable?

In [9]:
X = df[["engine-size"]]
y = df["price"]

lm1.fit(X,y)
#y_hat1 = lm1.predict(X)
#y_hat1[0:5]

LinearRegression()

In [10]:
lm1.fit(df[['engine-size']], df[['price']])
lm1

LinearRegression()

#### Question #1 c):
Find the slope and intercept of the model.

In [14]:

# slope
slope= lm1.coef_
print(slope)

[[166.86001569]]


In [15]:
# Intercept
intercept= lm1.intercept_
print(intercept)

[-7963.33890628]


#### Question #1 d): 
What is the equation of the predicted line? You can use x and yhat or "engine-size" or "price".

In [21]:
# using X and Y
# y_hat1 = a + bX
y_hat1= -7963.34 + 166.86*X

Price = -7963.34 + 166.86*df['engine-size']


### 1. Multiple Linear Regression
##### What if we want to predict car price using more than one variable?

If we want to use more variables in our model to predict car price, we can use Multiple Linear Regression. Multiple Linear Regression is very similar to Simple Linear Regression, but this method is used to explain the relationship between one continuous response (dependent) variable and two or more predictor (independent) variables. Most of the real-world regression models involve multiple predictors. We will illustrate the structure by using four predictor variables, but these results can generalize to any integer:

From the previous section we know that other good predictors of price could be:

- Horsepower
- Curb-weight
- Engine-size
- Highway-mpg
  
Let's develop a model using these variables as the predictor variables.

In [25]:
Z = df[["horsepower", "curb-weight", "engine-size", "highway-mpg"]]

lm3 = LinearRegression()
#Fit the linear model using the four above-mentioned variables.
lm3.fit(Z, df["price"])

LinearRegression()

In [26]:
# What is the value of the intercept(a)?
lm3.intercept_

-15806.624626329201

In [28]:
# What are the values of the coefficients (b1, b2, b3, b4)?
lm3.coef_

array([53.49574423,  4.70770099, 81.53026382, 36.05748882])

#### Question #2 a): 
Create and train a Multiple Linear Regression model "lm2" where the response variable is "price", and the predictor variable is "normalized-losses" and "highway-mpg".

In [30]:
# Predictors
X = df[["normalized-losses", "highway-mpg"]]
#target
y = df["price"]

lm4 = LinearRegression()

# Fit the linear model
lm4.fit(X,y)

LinearRegression()

In [31]:
# Question #2 b): 
# Find the coefficient of the model.

lm4.coef_

array([   1.49789586, -820.45434016])

### 2. Model Evaluation Using Visualization
Now that we've developed some models, how do we evaluate our models and choose the best one? One way to do this is by using a visualization.

Import the visualization package, seaborn: